### ISSUE TITLE
content updates not appearing on the website

### ISSUE THREAD

**Issue by aaronmarkham** [mli/new-docs#126]
Compare:
https://beta.mxnet.io/api/ndarray/index.html
to
https://github.com/mli/new-docs/pull/122/files#diff-cc7e543ab494e686223548eaa26c0cf2

Is CI not running? I'm seeing other strange behavior too. The navigation seems broken.

**Comment by IvyBazan** [comment]
Also missing updated content on:
https://beta.mxnet.io/api/gluon-related/index.html
https://beta.mxnet.io/api/symbol/index.html
https://beta.mxnet.io/api/symbol-related/index.html
https://beta.mxnet.io/api/advanced/index.html

**Comment by IvyBazan** [comment]
Fixes to images missing from the autograd page:
https://beta.mxnet.io/guide/packages/autograd/autograd.html

**Comment by IvyBazan** [comment]
The latest content pulled from master contains the content missing from the beta site

**Comment by aaronmarkham** [comment]
moot now that we launched
